### ISSUE TITLE
Is there any update to this ?

### ISSUE THREAD

**Issue by vigneshrams** [adamakhtar/tincanz#1]
Hi,

I love to work on this project and implement as in my Webapp replacing Intercom messaging. So can you help doing it. Is the messaging fully functional. How can i set it up for my webapp ?

Please help.
Thanks

**Comment by adamakhtar** [comment]
Hi @vigneshrams 

Sorry for delay - I've been on holiday and not been online so much. Unfortunately I stopped work on Tincanz last yeasr and I've been meaning to update the readme (Ill do that now). It wasnt near a useable state so you may want to look for something else in the meantime.

I have however been working on a gem called Hightower which allows you to watch for user behaviour and automate responding to it (i.e. like intercom). It's a small simple gem but you can use it now though I'm sure theres some discrepancies in the Readme I haven't noticed.  You can fine it here 
https://github.com/robodisco/hightower

Let me know if you have any other questions.

Adam

**Comment by vigneshrams** [comment]
Hi,

Thanks for the reply. I am going to use hightower for my sideprojects.

BTW if you have any idea of working on startup of your own I would love to join you. Hope I can learn a lot from you.

**Comment by adamakhtar** [comment]
Thanks @vigneshrams I hope Hightower is useful for your projects. Let me know in the issue tracker for Hightower if you spot any bugs or have any ideas for features. 

Re: Startups i'm currently on a nice long break from such adventures :smile:  and just enjoying my current job and open source contributions. If things change ill remember your offer and get in touch.
